source(output(
		emp_id as integer,
		emp_name as string,
		emp_date_of_birth as date,
		emp_address as string,
		emp_phone as string,
		emp_email as string,
		emp_salary as decimal(18,0),
		emp_position as string,
		bran_id as integer,
		emp_join_date as date,
		emp_type as string
	),
	allowSchemaDrift: true,
	validateSchema: false,
	ignoreNoFilesFound: false,
	format: 'parquet') ~> sourceEmployee
sourceEmployee select(mapColumn(
		emp_id,
		emp_name,
		emp_address,
		emp_phone,
		emp_email,
		emp_salary,
		emp_position,
		emp_type,
		emp_date_of_birth,
		emp_join_date
	),
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true) ~> selectEmployee
selectEmployee sink(allowSchemaDrift: true,
	validateSchema: false,
	input(
		emp_id as integer,
		emp_name as string,
		emp_address as string,
		emp_phone as string,
		emp_email as string,
		emp_salary as decimal(18,0),
		emp_position as string,
		emp_type as string,
		emp_date_of_birth as date,
		emp_join_date as date
	),
	deletable:false,
	insertable:true,
	updateable:false,
	upsertable:false,
	format: 'table',
	staged: true,
	allowCopyCommand: true,
	preSQLs:['SET IDENTITY_INSERT [dbo].[Dim_Employee] ON'],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true,
	errorHandlingOption: 'stopOnFirstError') ~> sinkEmployee